### sign in
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
  "username": "moimoi",
  "email": "momoi@gmail.com",
  "full_name": "momo ayase",
  "password": "agmer1234"
}

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username" : "agmer_dev",
  "password" : "agmer1234"
}

### get profile (me)
GET http://localhost:3000/api/users/@me
Authorization:Bearer eyJhbGciOiJIUzM4NCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZ21lcl9kZXYiLCJpYXQiOjE3NTQ0MDEyNjEsImV4cCI6MTc1NDQ4NzY2MX0.Fqudxc96NfOLYOXNqexXv6fyka-0D23IXf9tBmkNhJZOR4Q226muRcHJgihY2PnH
Accept: application/json

