### sign in
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
  "username": "agmer_dev",
  "email": "agmer@gmail.com",
  "full_name": "rizky ramadhan agmer",
  "password": "agmer1234"
}

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username" : "agmer_dev",
  "password" : "agmer1234"
}

### get profile (me)
GET http://localhost:3000/api/users/@me
Authorization:Bearer eyJhbGciOiJIUzM4NCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiYWdtZXIxMjM0IiwiaWF0IjoxNzU0MjAxNjcxLCJleHAiOjE3NTQyODgwNzF9.wIGRmICu8Wzjx38hzTrmKnI73ePb1EB6XhIFZcT2xSWDE7rPMQZGZA3CQPr144Mt
Accept: application/json

