### sign in
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
  "username": "moimoi",
  "email": "momoi@gmail.com",
  "full_name": "momo ayase",
  "password": "agmer1234"
}

### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username" : "agmer_dev",
  "password" : "agmer1234"
}

### get profile (me)
GET http://localhost:3000/api/users/@me
Authorization:Bearer eyJhbGciOiJIUzM4NCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZ21lcl9kZXYiLCJpYXQiOjE3NTQ0MDEyNjEsImV4cCI6MTc1NDQ4NzY2MX0.Fqudxc96NfOLYOXNqexXv6fyka-0D23IXf9tBmkNhJZOR4Q226muRcHJgihY2PnH
Accept: application/json

### get another user profile
GET http://localhost:3000/api/users/marin_chan
Authorization:Bearer eyJhbGciOiJIUzM4NCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZ21lcl9kZXYiLCJpYXQiOjE3NTQ0MDEyNjEsImV4cCI6MTc1NDQ4NzY2MX0.Fqudxc96NfOLYOXNqexXv6fyka-0D23IXf9tBmkNhJZOR4Q226muRcHJgihY2PnH
Accept: application/json

### get Post data
GET http://localhost:3000/api/posts/068f6939-ef0b-4174-8cf8-14d8a4b2218e

### UPLOADS
POST http://localhost:3000/api/posts
Authorization:Bearer eyJhbGciOiJIUzM4NCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZ21lcl9kZXYiLCJpYXQiOjE3NTQ0ODcxMzUsImV4cCI6MTc1NDU3MzUzNX0.Y1UvSMkmTqnv_rZLfk1SBfWt0qgKc52HcOzOXJCtHh5_LZZ43zTBHYQvlhJ73rX0

POST http://localhost:8080/api/posts
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="text_content"

Ini adalah konten teks post
--boundary
Content-Disposition: form-data; name="media"; filename="contoh.jpg"
Content-Type: image/jpeg

< ./contoh.jpg
--boundary--



